### ISSUE TITLE
error: could not open file "[filename.png]"

### ISSUE THREAD

**Issue by WildPilot1** [RickdeJager/stegseek#10]
I'm confident I'm doing something wrong here but, I'm trying to crack an image from a riddle.... I followed instructions with Powershell/Ubuntu and have the stegseek build running. when i try to crack the filename i get that error message. im new to all this and your build was my first so bare with me.

**Comment by RickdeJager** [comment]
Hey, it seems there are two separate issues here:
* Firstly, that error message indicates that Stegseek was not able to read the file you specified. This is most likely either a path issue (misspelled filename, or the file is in a different directory), or a permission issue, ie does your current user have read permissions on the file?  
* Second, Steghide (and by extension Stegseek) does not have support for PNG files at the moment, so the file you're trying to crack probably does not contain Steghide data.  
  
If you need more help, please provide some more context so I have an idea of what might be going wrong, for example:
* the file you're using
* the permissions (`ls -lash`)
* the command you're executing

**Comment by WildPilot1** [comment]
I think the main problem im having it a path issue. the file is on my windows hard drive... after a few youtube videos, i did manage to get the file uploaded to my github public repository.. and now my third issue will be it being a .png.. I think there is some hidden language in it. when i open it up with notepad and scroll to the bottom it says "the sound of silence" but i think there is more to it..
![x12yskkazotq](https://user-images.githubusercontent.com/94103239/141683699-be71749f-8645-408b-b35e-41acf752f7f8.png)
any other ways to crack a png file?

**Comment by RickdeJager** [comment]
When using WSL. you can access all of your Windows files from `/mnt/c/whatever/path/you/need`. You can also navigate to the file in Windows explorer and hit shift+right click -> `Open Linux shell here` to have WSL go to the correct folder directly.  
  
As for PNG's, Stegseek can't help you there. You might have more luck with zsteg/stegsolve or [some other stego tool](https://0xrick.github.io/lists/stego/). It could also be a case of unswirling the images content, but that's up to you to figure out :wink:.

Closing this for now, since I don't think this is a Stegseek issue, good luck with the riddle
